language: bash
sudo: required
#services:
#- docker
before_install:
- pushd travis-ci-test && ./setupenv.sh && popd

script:
- pushd travis-ci-test && ./runtest_basic.sh && popd
- pushd travis-ci-test && ./runtest_kill.sh && popd

